// ── Cassi v1 Engineering Handoff — Data ─────────────────────────────────────
// 9 UX projects in target-date order. Each contains sub-issues from Linear.
// This is the single source of truth for the handoff package.

export interface SubIssue {
  id: string;           // e.g. "UX-208"
  title: string;
  platform: string;     // "Desktop/iPad" | "Mobile Admin" | "Mobile PM" | "Mobile" | etc
  status: "Backlog" | "Todo" | "In Progress" | "Done" | "Cancelled";
  url: string;          // Linear link
  prototypeUrl?: string;       // link to interactive prototype (ux-homeos.vercel.app/proto/[slug])
  prd?: string;                // what this feature is and how it works — no ambiguity
  successCriteria?: string[];  // verifiable acceptance criteria for eng
  children?: { id: string; title: string; label: string }[]; // page states / features
}

export interface CustomerQuote {
  text: string;
  source: string;      // "Neversweat Apr 15" etc.
  person?: string;     // "Michael", "Karli", etc.
}

export interface ProjectContext {
  problem: string;              // What's broken today
  hypothesis: string;           // What we believe will fix it
  evidence: CustomerQuote[];    // Direct quotes from pilot research
  successSignal: string;        // How we know it worked
  researchFlags?: string[];     // Tensions or open questions from research
}

export interface Project {
  id: number;
  name: string;
  linearProjectId: string;
  linearUrl: string;
  status: "Planned" | "In Progress" | "Backlog";
  targetDate: string | null;  // "Apr 22" etc.
  color: string;
  prototypeUrl?: string;      // link to interactive prototype on Vercel
  context: ProjectContext;     // the WHY
  issues: SubIssue[];
}

const PROTO_BASE = "https://ux-homeos.vercel.app";

export const PROJECTS: Project[] = [
  // ── 1. Navigation & Site Structure ────────────────────────
  {
    id: 1,
    name: "Navigation & Site Structure",
    linearProjectId: "1bacdcb5-91e4-4a11-ad4a-9e18746cec13",
    linearUrl: "https://linear.app/cassi/project/navigation-and-site-structure-926546ed3894",
    status: "Planned",
    targetDate: "Apr 22",
    color: "#bec2c8",
    context: {
      problem: "Too many clicks to get anywhere. The beta had deep nesting; the prototype improved this but customers still report friction reaching key views. Calendar buried, tasks require multiple navigations.",
      hypothesis: "A flat navigation with calendar as home and everything else one tap away will match how PMs actually think — schedule first, then drill into specifics.",
      evidence: [
        { text: "Too many clicks to reach the calendar view.", source: "Wellen + Neversweat", person: "Karli / Michael" },
        { text: "I love how simple this is… I could learn this in a couple hours.", source: "Old World", person: "Patrick" },
        { text: "Fewer clicks = better.", source: "Neversweat", person: "Michael" },
      ],
      successSignal: "PM can reach any core view (calendar, tasks, routines, properties, vendors) in 1 tap from any screen.",
    },
    issues: [
      { id: "UX-321", title: "Navigation", platform: "Desktop / iPad", status: "Backlog", url: "https://linear.app/cassi/issue/UX-321",
        prd: "Primary navigation for desktop and iPad. Persistent nav bar or dropdown that gives access to all core modules: Calendar (home), Properties, Tasks, Routines, Team, Vendors, Settings. Current module is visually indicated. Nav must not take significant screen real estate — the calendar is the primary content. Canvas overlays (Properties, Team, Vendors, Routines) open from nav without leaving the calendar context.",
        successCriteria: [
          "All core modules reachable in 1 tap from any screen",
          "Current location visually indicated in nav",
          "Nav does not obscure calendar content",
          "Canvas overlays open over calendar, close returns to calendar state",
          "Works on desktop (1440px+) and iPad (1024px)",
        ],
      },
      { id: "UX-322", title: "Navigation", platform: "Mobile", status: "Backlog", url: "https://linear.app/cassi/issue/UX-322",
        prd: "Mobile navigation for Admin and PM apps. Bottom tab bar with core modules. PM view may have fewer tabs than Admin. Tab bar must not obscure content. Active tab visually indicated. Supports Admin role (full access) and PM role (assigned work focus).",
        successCriteria: [
          "Bottom tab bar with core modules visible on every screen",
          "Active tab visually distinct",
          "Admin sees: Schedule, Tasks, Properties, More (Team/Vendors/Settings)",
          "PM sees: My Day, Tasks, Properties, More",
          "Tab bar does not overlap content or input areas",
        ],
      },
      { id: "UX-323", title: "Site Structure", platform: "Desktop / iPad", status: "Backlog", url: "https://linear.app/cassi/issue/UX-323",
        prd: "Information architecture and URL structure for the desktop app. Defines how modules relate to each other, what opens as canvas overlay vs. full page, breadcrumb behavior, and deep-link patterns. Calendar is home (/). Properties, Team, Vendors open as canvas overlays. Settings opens as canvas overlay. Task/routine detail opens as slide panel over calendar.",
        successCriteria: [
          "URL structure documented and consistent",
          "Calendar is the root view (/)",
          "Deep links work for: specific property, specific task, specific routine instance",
          "Browser back button behavior is predictable (close overlay → return to calendar)",
          "No dead-end states — every view has a clear way back",
        ],
      },
    ],
  },

  // ── 2. Calendar & Dashboard ───────────────────────────────
  {
    id: 2,
    name: "Calendar & Dashboard",
    linearProjectId: "bdbd751c-783b-4da8-a36e-9e190782f283",
    linearUrl: "https://linear.app/cassi/project/calendar-and-dashboard-e8b5b8d61eaf",
    status: "Planned",
    targetDate: "Apr 22",
    color: "#eb5757",
    prototypeUrl: `${PROTO_BASE}`,
    context: {
      problem: "PMs juggle schedules across properties, team, and vendors using memory, texts, and disconnected calendars. No single view shows what's happening across the portfolio. Events (contractor meetings) and reminders (flexible to-dos) have no home.",
      hypothesis: "Calendar as the primary interface — not a feature inside the app, but THE app — gives PMs the at-a-glance control they need. Events and reminders fill the gap between hard-scheduled tasks and things that need tracking but aren't work items.",
      evidence: [
        { text: "I loved that calendar. I thought it was great.", source: "Neversweat Apr 13", person: "Michael" },
        { text: "If someone calls for something crazy that has to be done in the next three days, where can we put it in? Right now I either say yes and I don't know if we can, or I say I'll get back to you, go to the computer, look at the big calendar.", source: "Neversweat Apr 15", person: "Michael" },
        { text: "I could just fly through these easily.", source: "Old World", person: "Patrick" },
        { text: "We just run in circles all day long basically.", source: "Wellen Apr 14", person: "Karli" },
      ],
      successSignal: "PM opens the app and immediately knows what's happening today across all properties, team, and vendors — without clicking into anything.",
      researchFlags: [
        "Divergent default view preferences — Old World/Wellen want calendar; Neversweat wants punch list first. Default should be configurable per company.",
        "Offline calendar access — Old World has properties with no connectivity. Architecture decision required before mobile scope is finalized.",
      ],
    },
    issues: [
      { id: "UX-208", title: "Schedule", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-208",
        prototypeUrl: `${PROTO_BASE}`,
        prd: "Calendar as the primary interface. Month, week, and day views showing all tasks, routines, and events across all properties. Color-coded by source: Team (lilac), Vendor (amber), Me (teal), Unassigned (gray). Filtering by source and property. Clicking empty slot opens task creation pre-filled with date/time. Clicking item opens detail slide panel. Overdue items visually distinct. Operational rail alongside calendar shows Cassi suggestions, team status, tasks, and routines in tabs.",
        successCriteria: [
          "Month/week/day views render all tasks, routines, and events",
          "Source filtering (All/Team/Vendor/Me) works",
          "Property filtering works from dropdown",
          "Click empty calendar slot → task creation with date/time pre-filled",
          "Click calendar item → detail panel opens",
          "Overdue items show red indicator",
          "Operational rail visible alongside calendar with Cassi/Team/Tasks/Routines tabs",
          "New user empty state shows guided action cards",
          "Calendar renders correctly on desktop (1440px+) and iPad (1024px)",
        ],
      },
      { id: "UX-218", title: "Schedule", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-218",
        prd: "Mobile calendar for Admin and PM. Day view as primary (shows today's schedule), with ability to swipe between days and access week/month views. Same color coding and filtering as desktop. Tap item to open detail. Floating action button for quick task creation.",
        successCriteria: [
          "Day view shows today's items by default",
          "Swipe between days",
          "Week and month views accessible",
          "Tap item → detail view",
          "Floating action button → task creation",
          "Source and property filtering available",
        ],
      },
      { id: "UX-236", title: "Dashboard Notifications", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-236",
        prototypeUrl: `${PROTO_BASE}/proto/dashboard-notifications`,
        prd: "Notification feed showing items that need PM attention: overdue tasks, vendor confirmations pending, QA reviews waiting, routine instances missed, homeowner messages. Grouped by urgency. Each notification is actionable — click to go to the relevant item. Clearable individually or in bulk. Badge count on nav when unread notifications exist.",
        successCriteria: [
          "Notifications grouped by urgency (urgent/today/this week)",
          "Each notification links to its source (task, routine, vendor, etc.)",
          "Click notification → opens relevant detail",
          "Individual dismiss and bulk clear",
          "Unread badge count visible in nav",
          "Empty state when no notifications",
          "Notifications for: overdue tasks, QA pending, vendor no-response, missed routines",
        ],
      },
      { id: "UX-237", title: "Dashboard Notifications", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-237",
        prototypeUrl: `${PROTO_BASE}/proto/dashboard-notifications`,
        prd: "Mobile notification feed. Same content as desktop but optimized for touch. Push notification integration for urgent items. Tap to navigate to source item.",
        successCriteria: [
          "Push notifications for urgent items",
          "Notification feed accessible from nav",
          "Tap notification → navigates to source",
          "Swipe to dismiss individual notifications",
        ],
      },
      { id: "UX-238", title: "Cassi Insights", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-238",
        prd: "AI-powered suggestion feed in the operational rail. Two tiers: high-stakes suggestions (cards with approve/dismiss/alternative actions) and one-liner actions (quick items). Cassi generates suggestions based on: overdue items, scheduling conflicts, vendor follow-ups needed, maintenance patterns, team availability. PM can approve, dismiss, or modify each suggestion. Dismissed suggestions are logged for Cassi learning.",
        successCriteria: [
          "High-stakes suggestion cards with approve/dismiss/alternative actions",
          "One-liner action items below suggestions",
          "Suggestions refresh based on operational state",
          "Approve action executes (creates task, sends notification, etc.)",
          "Dismiss logs the decision for future learning",
          "Cassi daily briefing at top of rail summarizing the day",
        ],
      },
      { id: "UX-239", title: "Cassi Insights", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-239",
        prd: "Mobile Cassi insights. Condensed suggestion cards optimized for touch. Focus on the top 3 most important items for the PM's current context (location, time of day, active tasks).",
        successCriteria: [
          "Top 3 suggestions shown, expandable for more",
          "Approve/dismiss with single tap",
          "Context-aware: shows relevant suggestions based on PM's current situation",
        ],
      },
      { id: "UX-230", title: "Team Dispatch", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-230",
        prototypeUrl: `${PROTO_BASE}/proto/team-dispatch`,
        prd: "Visual dispatch board showing each team member's daily schedule as a Gantt-style row. Shows: who is going where, at what time, for what task/routine. Unscheduled tasks in a sidebar queue for drag-and-drop assignment. Cassi surfaces scheduling efficiency suggestions (bundle visits at same property, optimize routing). Shows current location/property per team member.",
        successCriteria: [
          "Each team member shown as a row with time blocks for their tasks/routines",
          "Unscheduled task queue visible alongside dispatch board",
          "Cassi scheduling suggestions visible (bundle, optimize)",
          "Current location/property per team member shown",
          "Day and week view toggle",
          "Empty state when no team members",
          "Full state with multiple team members and overlapping schedules",
        ],
      },
      { id: "UX-233", title: "Team Dispatch", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-233",
        prototypeUrl: `${PROTO_BASE}/proto/team-dispatch`,
        prd: "Mobile dispatch view. Simplified list of team members with today's assignments. Tap team member to see their full day schedule. Admin can reassign tasks from this view.",
        successCriteria: [
          "List of team members with today's task count",
          "Tap → see team member's day schedule",
          "Reassign task action available",
        ],
      },
      { id: "UX-186", title: "Team Member Schedule", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-186",
        prd: "Individual team member's schedule view — daily and weekly Gantt showing all assigned tasks and routines. Working hours displayed as boundaries. Time off blocks visible. Shows travel time estimates between properties if available.",
        successCriteria: [
          "Daily and weekly Gantt for individual team member",
          "Working hours shown as background boundaries",
          "Time off blocks visible and non-schedulable",
          "Tasks and routines shown with property, time window, and status",
        ],
      },
      { id: "UX-193", title: "Team Member Schedule", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-193",
        prd: "Mobile view of a team member's schedule. Day view showing ordered task list with times and properties. PM role sees only their own schedule.",
        successCriteria: [
          "Day view with ordered task/routine list",
          "Each item shows property, time window, status",
          "PM sees own schedule; Admin sees any team member's schedule",
        ],
      },
      { id: "UX-200", title: "Team Utilization Status", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-200",
        prd: "Utilization indicator per team member showing: Open (has capacity), Overbooked (more tasks than hours available). Calculated from working hours minus scheduled task durations. Visible on team list and dispatch views. Cassi flags overbooked team members in suggestions.",
        successCriteria: [
          "Open/Overbooked status visible per team member",
          "Calculation based on working hours vs. scheduled task durations",
          "Visible on both team list and dispatch board",
          "Cassi flags overbooked members in insight suggestions",
        ],
      },
      { id: "UX-203", title: "Team Utilization Status", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-203",
        prd: "Mobile utilization badge on team list. Simple Open/Overbooked indicator per team member.",
        successCriteria: [
          "Badge visible on team member list items",
          "Open = green, Overbooked = red/amber indicator",
        ],
      },
      { id: "UX-206", title: "Time Off Designation", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-206",
        prd: "Admin can set time off for team members (vacation, sick, personal). Time off blocks appear on team member's schedule and dispatch board as non-schedulable. System prevents scheduling tasks during time off. Editable — Admin can add, modify, remove time off blocks.",
        successCriteria: [
          "Admin can create time off block with date range and reason",
          "Time off blocks visible on schedule and dispatch views",
          "System prevents scheduling during time off periods",
          "Edit and remove time off blocks",
        ],
      },
      { id: "UX-164", title: "Create an Event", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-164",
        prd: "Calendar events that are NOT tasks or routines — contractor meetings, homeowner walkthroughs, personal blocks, vendor site visits. No status flow (events are just calendar blocks). Fields: Title, Date/time, Duration, Property (optional), Notes. Created from calendar empty slot click or '+' button. Visually distinct from tasks and routines on calendar. Edit and delete with confirmation.",
        successCriteria: [
          "Create event from calendar (click empty slot or + button)",
          "Fields: title, date/time, duration, property (optional), notes",
          "Events render on calendar with distinct visual style (different from tasks/routines)",
          "Edit event: all fields editable",
          "Delete event with confirmation dialog",
          "Events do not have a status flow — no Open/In Progress/Complete",
          "Conflict indicator when event overlaps other items at same property",
        ],
      },
      { id: "UX-169", title: "Create an Event", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-169",
        prd: "Mobile event creation. Same fields as desktop. Accessible from calendar tap or floating action button. Quick creation flow — title and time required, everything else optional.",
        successCriteria: [
          "Create event from calendar or FAB",
          "Title and time required; property and notes optional",
          "Event visible on mobile calendar after creation",
          "Edit and delete supported",
        ],
      },
      { id: "UX-174", title: "Create a Reminder", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-174",
        prd: "Lightweight reminders — just a title and optional date. Lighter than tasks: no assignment, no status flow, no rules. Can be scheduled (appears on calendar) or unscheduled (lives in reminders bucket). Key actions: Convert to Task (opens task creation pre-filled), Add to Routine (opens routine selection). Delete with confirmation. Visually lighter than tasks on calendar.",
        successCriteria: [
          "Quick-create: just title + optional date, nothing else required",
          "Scheduled reminders appear on calendar with distinct visual",
          "Unscheduled reminders visible in a reminders list/bucket",
          "Convert to Task action: opens task creation pre-filled with reminder text, removes reminder",
          "Add to Routine action: opens routine selection, adds as new action",
          "Delete with confirmation",
          "Reminders visually lighter than tasks on calendar",
        ],
      },
      { id: "UX-180", title: "Create a Reminder", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-180",
        prd: "Mobile reminder creation. Ultra-quick — type title, optionally set date, done. Same convert-to-task and add-to-routine actions as desktop.",
        successCriteria: [
          "Create reminder in under 10 seconds",
          "Optional date picker",
          "Convert to Task and Add to Routine actions available",
          "Reminders list accessible from nav",
        ],
      },
    ],
  },

  // ── 3. Properties ─────────────────────────────────────────
  {
    id: 3,
    name: "Properties",
    linearProjectId: "acdb6e04-c82f-4b64-b974-7657c8fd0fac",
    linearUrl: "https://linear.app/cassi/project/properties-6e9326590831",
    status: "Planned",
    targetDate: "Apr 27",
    color: "#5e6ad2",
    context: {
      problem: "Service history per property is critical and currently missing. PMs rely on memory and texts. Different techs visit the same property and don't share notes. Access codes, vendor contacts, and asset info live in disconnected systems (Ignite, notebooks, text threads).",
      hypothesis: "A property profile with structured knowledge base (assets, documents, photos, notes, access info) eliminates the tribal knowledge problem. AI-powered onboarding from uploaded documents means PMs don't re-enter what they already have.",
      evidence: [
        { text: "If we could be like: Jack was on site and fixed this, this, and this, and these were his notes — we can compare.", source: "Wellen Apr 14", person: "Karli" },
        { text: "I would want to get as much information up front so I can set up services because if I'm going to set up their HVAC service, they're going to ask, 'Well, what equipment do they have?'", source: "Wellen Apr 14", person: "Karli" },
        { text: "My guys should not be calling me and saying, 'Who's the vendor at this property?' You should just see it and you should just call them.", source: "Wellen Apr 14", person: "Karli" },
      ],
      successSignal: "A tech arrives at a property and has everything they need (access codes, asset history, vendor contacts, prior notes) without calling the PM.",
      researchFlags: [
        "Assets tab deferred from v1 — but Wellen's HVAC story and Neversweat's asset tracking needs are real. A lightweight asset reference within the task model may need to ship even if full asset management is post-v1.",
        "Bulk property creation deferred — TMS (80 properties) and Neversweat (50–60) cannot onboard at scale without it.",
        "20-property hard cap bug — Neversweat: adding a 21st causes the last to disappear. Blocking adoption.",
      ],
    },
    issues: [
      { id: "UX-34", title: "Property Onboarding — Documentation", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-34",
        prd: "Property onboarding via document upload. PM uploads existing property documentation (management agreements, inspection reports, HOA docs, etc.) and Cassi extracts property details: address, owner info, access codes, asset inventory, vendor contacts, service history. Extraction runs async — PM sees a processing state, then a pre-filled property profile to review. Handles partial extraction (missing fields highlighted for manual entry) and upload failures (retry with clear error message). Supported formats: PDF, DOCX, images of documents.",
        successCriteria: [
          "PM can upload one or more documents (PDF, DOCX, images)",
          "Processing state shown while Cassi extracts data",
          "Success state: pre-filled property profile with extracted fields",
          "Missing fields state: extracted fields shown, missing fields highlighted with manual entry prompts",
          "Upload failure state: clear error message with retry action",
          "Extracted data is editable before activation",
          "Multiple documents can be uploaded in a single onboarding session",
        ],
        children: [
          { id: "UX-41", title: "Success", label: "page state" },
          { id: "UX-42", title: "Missing Fields", label: "page state" },
          { id: "UX-43", title: "Failure to upload", label: "page state" },
        ],
      },
      { id: "UX-35", title: "Property Onboarding — Scratch", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-35",
        prd: "Property onboarding from scratch — manual form entry on desktop/iPad. Multi-step form: address and basic info, owner/contact details, access codes, service preferences, optional asset inventory. Cassi may suggest auto-fill for fields like timezone or HOA based on address. Required fields: property name, address. All other fields optional to allow quick creation. Success state confirms creation and prompts PM to review full profile. Missing fields state saves progress and flags incomplete sections.",
        successCriteria: [
          "Multi-step form with clear progress indicator",
          "Required fields: property name and address",
          "All other fields optional — PM can skip and fill later",
          "Success state: confirmation with link to property profile",
          "Missing fields state: saved draft with incomplete sections flagged",
          "Form preserves progress if PM navigates away and returns",
          "Address field supports autocomplete",
        ],
        children: [
          { id: "UX-36", title: "Success", label: "page state" },
          { id: "UX-37", title: "Missing Fields", label: "page state" },
        ],
      },
      { id: "UX-38", title: "Property Onboarding — Scratch", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-38",
        prd: "Mobile property onboarding from scratch. Same fields as desktop but optimized for mobile input. Single-scroll form or step-by-step wizard. Camera integration for capturing property photos during setup. Address autocomplete with GPS-based suggestion. Minimal required fields (name + address) to enable quick on-site creation.",
        successCriteria: [
          "Property creation in under 2 minutes with just name and address",
          "Success state: confirmation with link to property profile",
          "Missing fields state: saved draft with flagged incomplete sections",
          "Camera integration for property photo capture",
          "Address autocomplete with GPS-based suggestion",
          "Form state preserved on interruption (phone call, app background)",
        ],
        children: [
          { id: "UX-39", title: "Success", label: "page state" },
          { id: "UX-40", title: "Missing Fields", label: "page state" },
        ],
      },
      { id: "UX-44", title: "Property Onboarding — Review & Activate", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-44",
        prd: "Review screen after property onboarding (from docs or scratch). Shows all extracted/entered property data in a structured preview. PM reviews each section, edits inline, and activates the property. Activation changes property status from 'Setting Up' to 'Active'. Error/In-Progress state handles: extraction still processing, validation errors (e.g., duplicate address), or missing required fields. PM can save as draft (stays in 'Setting Up') or activate.",
        successCriteria: [
          "All property data shown in structured, reviewable sections",
          "Inline editing for any field",
          "Activate button changes status to Active",
          "Save as Draft keeps status as Setting Up",
          "Error state: validation errors shown inline with clear messages",
          "In-Progress state: extraction still running, polling with progress indicator",
          "Duplicate address warning with option to proceed or merge",
        ],
        children: [
          { id: "UX-45", title: "Success", label: "page state" },
          { id: "UX-46", title: "Error/In-Progress", label: "page state" },
        ],
      },
      { id: "UX-61", title: "Property Onboarding — Review & Activate", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-61",
        prd: "Mobile review and activation of an onboarded property. Same content as desktop but optimized for vertical scroll. Section-by-section review with expand/collapse. Inline editing with mobile-optimized inputs. Activate or save as draft actions pinned at bottom.",
        successCriteria: [
          "Section-by-section review with expand/collapse",
          "Inline editing with mobile-optimized inputs",
          "Activate button changes status to Active",
          "Save as Draft keeps status as Setting Up",
          "Error state: validation errors shown with clear messages",
          "In-Progress state: processing indicator while extraction completes",
        ],
        children: [
          { id: "UX-62", title: "Success", label: "page state" },
          { id: "UX-63", title: "Error/In-Progress", label: "page state" },
        ],
      },
      { id: "UX-47", title: "Property List", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-47",
        prd: "Property list view on desktop/iPad showing all properties in the organization. Each property card shows: name, address, status badge (Setting Up / Review / Active / Disabled), thumbnail photo, and quick stats (active tasks, upcoming routines). Filterable by status. Searchable by name or address. Sortable by name, status, or last activity. Click property to open property profile. Add Property button triggers onboarding flow. Opens as a canvas overlay from nav, not a full page navigation.",
        successCriteria: [
          "All properties displayed with name, address, status badge, thumbnail",
          "Filter by status: Setting Up, Review, Active, Disabled",
          "Search by property name or address",
          "Sort by name, status, or last activity",
          "Click property → opens property profile",
          "Add Property button → triggers onboarding flow selection (docs or scratch)",
          "Empty state with guided prompt to add first property",
          "Canvas overlay from nav — does not leave calendar context",
        ],
      },
      { id: "UX-51", title: "Property List", platform: "Mobile Admin", status: "Todo", url: "https://linear.app/cassi/issue/UX-51",
        prd: "Mobile property list for Admin role. Full list of all org properties with search, status filter, and tap to open profile. Admin sees all properties regardless of assignment. Pull-to-refresh. Add Property action accessible from this view.",
        successCriteria: [
          "All org properties listed with name, address, status badge",
          "Search by name or address",
          "Filter by status",
          "Tap property → opens property profile",
          "Add Property action available",
          "Pull-to-refresh updates list",
          "Empty state prompts property creation",
        ],
      },
      { id: "UX-55", title: "Property List", platform: "Mobile PM", status: "Todo", url: "https://linear.app/cassi/issue/UX-55",
        prd: "Mobile property list for PM role. Shows only properties assigned to this PM. Same card format as Admin but scoped to PM's portfolio. No Add Property action (Admin only). Tap to open property profile.",
        successCriteria: [
          "Only PM's assigned properties shown",
          "Search by name or address",
          "Filter by status",
          "Tap property → opens property profile",
          "No Add Property action visible",
          "Pull-to-refresh updates list",
        ],
      },
      { id: "UX-64", title: "Property Profile — Knowledge Base", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-64",
        prd: "Property profile page on desktop/iPad. The single source of truth for everything about a property. Sections: Overview (address, owner, access codes, status), Documents (uploaded files — management agreements, inspection reports, HOA docs), Photos (property photos with captions and dates), Notes (running log of property-level notes from tasks and manual entries), Assets (linked asset list — see Manage Assets), Service History (chronological list of completed tasks and routines at this property), Vendors (vendors associated with this property). Each section is a tab or scrollable section. Admin can edit all fields. PM can view all, edit notes and photos. Access codes have a show/hide toggle for security.",
        successCriteria: [
          "Overview section: address, owner info, access codes (show/hide toggle), status",
          "Documents section: upload, view, download, delete files",
          "Photos section: upload, view, caption, delete photos",
          "Notes section: running log with author and timestamp, add new note",
          "Assets section: linked asset list with quick view",
          "Service History section: chronological completed tasks and routines",
          "Vendors section: vendors associated with this property",
          "Admin can edit all fields; PM can edit notes and photos",
          "Property status management: Active, Disabled with confirmation",
        ],
      },
      { id: "UX-58", title: "Property Profile — Knowledge Base", platform: "Mobile Admin", status: "Todo", url: "https://linear.app/cassi/issue/UX-58",
        prd: "Mobile property profile for Admin. Same content sections as desktop (Overview, Documents, Photos, Notes, Assets, Service History, Vendors) in a vertical tab or segmented view. Admin has full edit access. Camera integration for adding photos directly. Access codes with show/hide toggle. Quick actions: create task at this property, add note, upload photo.",
        successCriteria: [
          "All profile sections accessible via tabs or segments",
          "Full edit access for Admin on all fields",
          "Camera integration for photo upload",
          "Access codes with show/hide toggle",
          "Quick actions: create task, add note, upload photo",
          "Service history scrollable with load-more pagination",
        ],
      },
      { id: "UX-69", title: "Property Profile — Knowledge Base", platform: "Mobile PM", status: "Todo", url: "https://linear.app/cassi/issue/UX-69",
        prd: "Mobile property profile for PM role. Same sections as Admin but with read-only restrictions on owner info, access codes, and status. PM can add notes and photos. PM can view documents, assets, service history, and vendors but cannot edit property-level settings. Optimized for field use — quick access to access codes, vendor contacts, and recent notes.",
        successCriteria: [
          "All profile sections viewable",
          "PM can add notes and photos",
          "PM cannot edit owner info, access codes, or property status",
          "Access codes viewable with show/hide toggle",
          "Vendor contacts accessible (tap to call/text)",
          "Recent notes and service history easily scannable",
        ],
      },
      { id: "UX-72", title: "Property Profile — Manage Assets", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-72",
        prd: "Asset management within the property profile on desktop/iPad. Assets are physical equipment at a property (HVAC units, water heaters, appliances, pools, etc.). Each asset has: name, category, make/model, serial number, install date, warranty info, photos, notes, and linked service history (tasks/routines that reference this asset). Admin can add, edit, and remove assets. Asset list is filterable by category. Assets can be linked to tasks during task creation so service history builds automatically.",
        successCriteria: [
          "Asset list within property profile, filterable by category",
          "Add asset: name, category, make/model, serial number, install date, warranty, photos, notes",
          "Edit asset: all fields editable inline",
          "Remove asset with confirmation",
          "Each asset shows linked service history (tasks that referenced it)",
          "Asset selectable during task creation to build service history",
          "Warranty expiration visible with upcoming-expiry indicator",
        ],
      },
      { id: "UX-77", title: "Property Profile — Manage Assets", platform: "Mobile Admin", status: "Todo", url: "https://linear.app/cassi/issue/UX-77",
        prd: "Mobile asset management for Admin. Same CRUD operations as desktop. Camera integration for capturing asset photos (nameplate, serial number, condition). Barcode/QR scan for serial number entry. Quick-add flow: photo + name + category is the minimum to create an asset. Full edit available after creation.",
        successCriteria: [
          "Asset list within property profile",
          "Quick-add: photo + name + category minimum",
          "Camera integration for asset photos",
          "Full edit for all asset fields",
          "Remove asset with confirmation",
          "Linked service history visible per asset",
        ],
      },
      { id: "UX-82", title: "Property Profile — Assets", platform: "Mobile PM", status: "Todo", url: "https://linear.app/cassi/issue/UX-82",
        prd: "Mobile asset view for PM role. Read-only asset list within property profile. PM can view asset details, photos, and service history but cannot add, edit, or remove assets. Useful for field reference — PM sees what equipment is at the property, its specs, and its maintenance history.",
        successCriteria: [
          "Asset list viewable within property profile",
          "Tap asset to view full details, photos, and service history",
          "No add, edit, or remove actions visible",
          "Asset info accessible offline if previously loaded",
        ],
      },
    ],
  },

  // ── 4. Cassi Chat & Insights ──────────────────────────────
  {
    id: 4,
    name: "Cassi Chat & Insights",
    linearProjectId: "5c88027b-626e-4236-98a7-45654f4906b4",
    linearUrl: "https://linear.app/cassi/project/cassi-chat-and-insights-3a86602f4925",
    status: "Planned",
    targetDate: "Apr 30",
    color: "#26B5CE",
    context: {
      problem: "AI features feel like 'smoke and mirrors' when they show noise instead of actionable signal. PMs want AI that saves them time on real decisions — not a chatbot that summarizes what they already know.",
      hypothesis: "Cassi earns trust by being useful in context: suggesting tasks when you're at a property with downtime, flagging maintenance revenue you're missing, pre-filling work orders from conversation. Intelligence embedded in workflows, not a separate chat screen.",
      evidence: [
        { text: "If you have extra time here are some things that can be done there that aren't scheduled that have to be done now between now and the next three months… kind of a suggestion almost.", source: "Neversweat Apr 15", person: "Michael" },
        { text: "We are losing out for one maintenance of the house revenue and just overall organization.", source: "Wellen Apr 14", person: "Karli" },
        { text: "AI insights panel showing noise rather than actionable signal — 'smoke and mirrors' undermines trust in AI layer.", source: "Old World Apr 15", person: "Patrick" },
      ],
      successSignal: "PM acts on a Cassi suggestion at least once per day without being prompted to open a chat.",
      researchFlags: [
        "AI opportunistic task suggestions confirmed x2 (Neversweat + Wellen independently) — location-aware task suggestions on property arrival is a natural early AI feature.",
        "JC Contracting asked for form-fill alongside AI chat, not to replace it.",
      ],
    },
    issues: [
      { id: "UX-299", title: "Task/Routine Creation Insights", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-299",
        prd: "AI insights embedded in the task and routine creation flows on desktop/iPad. When PM creates a task or routine, Cassi analyzes context (property, assignee, type of work, historical data) and surfaces recommendations inline: suggested duration based on similar past tasks, recommended assignee based on availability and skill, scheduling conflicts or bundles (e.g., 'Vendor X is already at this property Tuesday — schedule this then?'), related assets that may need attention. Recommendations appear as dismissible suggestion chips within the creation form, not as a separate panel. PM can accept (auto-fills field) or dismiss.",
        successCriteria: [
          "Suggestions appear inline during task/routine creation",
          "Duration suggestion based on historical similar tasks",
          "Assignee recommendation based on availability and property familiarity",
          "Scheduling conflict detection shown before save",
          "Bundle suggestion when another visit is already scheduled at same property",
          "Accept suggestion auto-fills the relevant field",
          "Dismiss removes suggestion without blocking creation flow",
          "No suggestions shown when insufficient data — degrades gracefully",
        ],
      },
      { id: "UX-301", title: "Task/Routine Creation Insights", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-301",
        prd: "Mobile version of task/routine creation insights. Same recommendation engine as desktop but presented as a compact suggestion bar below the active form field. Tap to accept, swipe to dismiss. Location-aware: if PM is at a property, Cassi can suggest opportunistic tasks (things due soon at this property). Fewer simultaneous suggestions than desktop — prioritize the single most impactful recommendation.",
        successCriteria: [
          "Suggestion bar appears below active field during creation",
          "Tap to accept, swipe to dismiss",
          "Location-aware suggestions when PM is at a property",
          "Single most impactful suggestion prioritized over multiple",
          "Graceful degradation when no suggestions available",
        ],
      },
      { id: "UX-300", title: "Utilization and Calendar Insights", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-300",
        prd: "AI insights for team utilization and calendar optimization on desktop/iPad. Surfaces in the operational rail alongside the calendar. Insights include: overbooked team members with rebalance suggestions, unassigned tasks approaching due date, scheduling gaps (idle time that could be filled), vendor follow-ups overdue, maintenance windows being missed (e.g., seasonal HVAC service). Each insight is an actionable card — PM can approve the suggested action, modify it, or dismiss. Insights refresh when calendar or team data changes.",
        successCriteria: [
          "Utilization insights: overbooked team members with rebalance suggestion",
          "Unassigned tasks approaching due date flagged",
          "Scheduling gap detection with fill suggestions",
          "Vendor follow-up overdue alerts",
          "Maintenance window reminders based on property/asset data",
          "Each insight card has approve, modify, and dismiss actions",
          "Insights refresh on calendar or team data change",
          "Empty state when no insights — positive message, not blank",
        ],
      },
      { id: "UX-302", title: "Utilization and Calendar Insights", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-302",
        prd: "Mobile utilization and calendar insights. Condensed insight cards optimized for touch. Focus on the most urgent items: who's overbooked today, what's unassigned and due soon, which vendor hasn't responded. Accessible from a dedicated section on the mobile schedule view or via notification-style alerts.",
        successCriteria: [
          "Top insights shown in condensed card format",
          "Approve/dismiss with single tap",
          "Urgent items prioritized (overbooked today, due today unassigned)",
          "Accessible from mobile schedule view",
          "Push notification for critical insights (optional, respects preferences)",
        ],
      },
      { id: "UX-303", title: "Cassi Chat", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-303",
        prd: "Cassi Chat on desktop/iPad — conversational AI interface for property management queries and actions. Opens as a slide panel or overlay. PM can ask questions about their portfolio ('What's overdue this week?', 'Which properties need HVAC service before summer?'), request actions ('Create a task for pool opening at 123 Main'), or get explanations ('Why did you suggest reassigning this?'). Cassi responds with structured answers, not just text — tables, task cards, property links. Go Deeper prompts: after each response, Cassi offers 2-3 contextual follow-up questions as tappable chips (e.g., after showing overdue tasks: 'Reassign these?' / 'Show by property' / 'Notify assignees'). Chat history persists within session. Actions taken via chat (create task, send notification) show confirmation before execution.",
        successCriteria: [
          "Chat opens as slide panel without leaving current context",
          "Natural language queries return structured responses (tables, cards, links)",
          "Action requests show confirmation before execution",
          "Go Deeper prompts: 2-3 contextual follow-up chips after each response",
          "Chat history persists within session",
          "Links in responses navigate to the relevant item (task, property, etc.)",
          "Loading state while Cassi processes complex queries",
          "Error state with retry for failed responses",
        ],
        children: [
          { id: "UX-304", title: "Go Deeper Prompts", label: "feature" },
        ],
      },
      { id: "UX-305", title: "Cassi Chat", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-305",
        prd: "Mobile Cassi Chat — full-screen conversational interface. Same capabilities as desktop: queries, actions, structured responses. Optimized for mobile input — voice input option alongside keyboard. Go Deeper prompts as tappable chips below each response. Quick-action shortcuts at top of chat for common requests ('What's my day look like?', 'Any overdue tasks?'). Actions require tap-to-confirm before execution.",
        successCriteria: [
          "Full-screen chat interface with keyboard and voice input",
          "Structured responses: cards, lists, links",
          "Go Deeper prompts as tappable chips after each response",
          "Quick-action shortcuts at top of chat",
          "Action confirmation before execution",
          "Chat history persists within session",
          "Links navigate to relevant items in the app",
        ],
        children: [
          { id: "UX-306", title: "Go Deeper Prompts", label: "feature" },
        ],
      },
    ],
  },

  // ── 5. Tasks & Routines ───────────────────────────────────
  {
    id: 5,
    name: "Tasks & Routines",
    linearProjectId: "ffa0f43a-efe2-498f-960e-154f39fa93fa",
    linearUrl: "https://linear.app/cassi/project/tasks-and-routines-b16bf0e2c6dc",
    status: "Planned",
    targetDate: "May 5",
    color: "#f7c8c1",
    prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
    context: {
      problem: "PMs lack structured task lists — they receive verbal or text instructions. No reliable way to schedule and track recurring maintenance. Tasks require a hard date but field work often has no fixed date. No QA/approval step — work gets marked 'done' with no PM review.",
      hypothesis: "Tasks with a full lifecycle (Open → In Progress → Ready for QA → Completed), configurable rules (photos/notes/invoice required), and flexible scheduling (dated, flexible, recurring) give PMs control without micromanagement. Routines as structured checklists with pass/fail turn tribal knowledge into repeatable processes.",
      evidence: [
        { text: "I write down everything in a notebook which is part of the issue that I have.", source: "Neversweat Apr 15", person: "Michael" },
        { text: "The more stuff you get done, the more you get paid and the more you can take on.", source: "Neversweat Apr 15", person: "Michael" },
        { text: "Any communication is going to go through it and any task — you're not going to text me one thing — anything is going to go through here.", source: "Wellen Apr 14", person: "Karli" },
        { text: "Task status can't be reverted — once a status is changed, can't go back to 'Scheduled.'", source: "Neversweat (bug report)" },
      ],
      successSignal: "PM can create, assign, and track a task end-to-end without leaving a single flow. Field tech can complete a task and log notes on mobile in under 60 seconds.",
      researchFlags: [
        "No subtasks constraint — Neversweat, JC Contracting, and TMS all requested nested task structures. Brief specifies 'only relationship-based task connections.' Must be communicated clearly.",
        "Tasks require a hard date today — no soft/floating capture mode. This is fixed in the prototype (flexible tasks).",
        "Inspection module is a competitive differentiator — JC Contracting reviewer holds a NY State Home Inspector license. If built correctly, covers a workflow Procore does poorly and Monday doesn't support.",
      ],
    },
    issues: [
      { id: "UX-95", title: "Task Creation", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-95",
        prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
        prd: "Task creation flow on desktop/iPad. Accessible from: calendar (click empty slot, date/time pre-filled), dashboard (+ button), property profile (property pre-filled), Cassi Chat (fields pre-filled from conversation). Fields: title (required), property (required), description, assignee (team member or vendor), date/time or flexible (no fixed date), estimated duration, priority (Low/Medium/High/Urgent), rules (require photos, require notes, require invoice, require admin approval), linked asset, recurrence (none, daily, weekly, biweekly, monthly, custom). Task starts in Open status on creation. Cassi insights appear inline during creation (see UX-299). Save creates the task and returns to source context.",
        successCriteria: [
          "Task creation accessible from calendar, dashboard, property profile, and Cassi Chat",
          "Pre-filled fields based on entry point (date from calendar, property from profile)",
          "Required fields: title and property",
          "Assignee picker: team members and vendors",
          "Date/time picker or 'Flexible' toggle for undated tasks",
          "Priority selector: Low, Medium, High, Urgent",
          "Rules toggles: require photos, notes, invoice, admin approval",
          "Asset linker: select from property's asset list",
          "Recurrence options: none, daily, weekly, biweekly, monthly, custom",
          "Task created in Open status",
          "Save returns to source context (calendar, dashboard, etc.)",
        ],
      },
      { id: "UX-106", title: "Task Creation", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-106",
        prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
        prd: "Mobile task creation. Same fields as desktop but optimized for mobile input. Accessible from: calendar (tap empty slot or FAB), dashboard FAB, property profile. Quick-create mode: title + property only, everything else optional. Full-create mode: all fields available. Camera shortcut for attaching a photo during creation. Location-aware: if PM is at a property, that property is pre-selected.",
        successCriteria: [
          "Quick-create: title + property, task created in under 15 seconds",
          "Full-create: all desktop fields available",
          "Accessible from calendar, dashboard FAB, property profile",
          "Camera shortcut for immediate photo attachment",
          "Location-aware: property pre-selected when PM is on-site",
          "Task created in Open status",
          "Form state preserved on interruption",
        ],
      },
      { id: "UX-117", title: "Task Card", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-117",
        prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
        prd: "Task detail card on desktop/iPad — the full lifecycle view of a single task. Opens as a slide panel over the calendar. Status flow: Open → In Progress → Ready for QA → Completed. Status can also be set to Cancelled at any point. Rules enforcement: if 'require photos' is on, task cannot move to Ready for QA without at least one photo attached. Same for notes, invoice. If 'require admin approval' is on, Ready for QA requires Admin to approve or reject (reject sends back to In Progress with feedback). Task card sections: header (title, status, priority, property, assignee, dates), description, field notes (added by assignee during work), photos (captured during work), invoice attachment, linked asset with service history, property notes (pulled from property profile for assignee reference), activity log (status changes, notes, timestamps). Edit: Admin can edit all fields. PM/assignee can add notes and photos, change status per rules.",
        successCriteria: [
          "Status flow: Open → In Progress → Ready for QA → Completed",
          "Cancel action available at any status",
          "Rules enforcement: photos/notes/invoice required blocks QA transition if missing",
          "Admin approval: QA state requires Admin approve or reject",
          "Reject sends task back to In Progress with Admin feedback",
          "Field notes: assignee adds notes during task execution",
          "Photo section: upload/capture photos, viewable gallery",
          "Invoice attachment: upload PDF/image",
          "Linked asset shown with service history snippet",
          "Property notes pulled from property profile for reference",
          "Activity log: all status changes and notes with timestamps",
          "Admin can edit all fields; PM/assignee limited to notes, photos, status",
        ],
      },
      { id: "UX-124", title: "Task Card", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-124",
        prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
        prd: "Mobile task card — optimized for field tech execution. Full-screen view of a single task. Same status flow and rules enforcement as desktop. Camera integration for photo capture (opens camera directly, not file picker). Quick status change button prominent at bottom. Field notes entry with keyboard and voice input. Invoice photo capture (snap a paper invoice). Property notes and access codes visible for field reference. Designed for one-handed use where possible.",
        successCriteria: [
          "Status flow: Open → In Progress → Ready for QA → Completed",
          "Rules enforcement same as desktop",
          "Camera opens directly for photo capture (not file picker)",
          "Quick status change button prominent at bottom of screen",
          "Field notes entry with keyboard",
          "Invoice capture via camera",
          "Property notes and access codes visible",
          "Task completion flow under 60 seconds for a simple task",
        ],
      },
      { id: "UX-85", title: "Task/Routine List — All", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-85",
        prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
        prd: "Master list of all tasks and routines across the organization on desktop/iPad. Filterable by: status (Open, In Progress, Ready for QA, Completed, Cancelled), type (Task/Routine), property, assignee, priority, date range. Sortable by: date, priority, status, property. Each row shows: title, property, assignee, status badge, priority, due date. Click row to open task/routine detail. Bulk actions: reassign, change priority, cancel. Pagination or infinite scroll for large lists. Tab toggle between Tasks and Routines.",
        successCriteria: [
          "All org tasks and routines listed",
          "Filter by: status, type, property, assignee, priority, date range",
          "Sort by: date, priority, status, property",
          "Each row: title, property, assignee, status badge, priority, due date",
          "Click row → opens detail panel",
          "Bulk actions: reassign, change priority, cancel",
          "Tab toggle: Tasks / Routines",
          "Empty state when no items match filters",
          "Pagination or infinite scroll for 100+ items",
        ],
      },
      { id: "UX-88", title: "Task/Routine List — All", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-88",
        prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
        prd: "Mobile master list of all tasks and routines. Same data as desktop but in a card-based scrollable list. Filter sheet accessible via filter icon. Search bar at top. Tap card to open detail. Pull-to-refresh. Tab toggle between Tasks and Routines.",
        successCriteria: [
          "All org tasks and routines in card list",
          "Filter sheet: status, type, property, assignee, priority",
          "Search by title or property name",
          "Tap card → opens detail view",
          "Pull-to-refresh",
          "Tab toggle: Tasks / Routines",
        ],
      },
      { id: "UX-91", title: "Task/Routine List — Assigned", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-91",
        prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
        prd: "Filtered view showing only tasks and routines assigned to the logged-in user on desktop/iPad. Same layout and interaction as the All list but pre-filtered to current user. Grouped by: Today, Upcoming, Overdue, Flexible (no date). Quick status change available inline without opening detail. This is the PM's 'My Work' view.",
        successCriteria: [
          "Only current user's assigned tasks and routines shown",
          "Grouped by: Today, Upcoming, Overdue, Flexible",
          "Inline quick status change without opening detail",
          "Additional filters still available (property, priority, type)",
          "Click row → opens detail panel",
          "Empty state: 'No tasks assigned' with link to all tasks",
        ],
      },
      { id: "UX-92", title: "Task/Routine List — Assigned", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-92",
        prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
        prd: "Mobile view of tasks and routines assigned to the current user. Card-based list grouped by Today, Upcoming, Overdue, Flexible. Swipe actions for quick status change. This is the primary view for PM mobile app — their daily work queue.",
        successCriteria: [
          "Only current user's assignments shown",
          "Grouped: Today, Upcoming, Overdue, Flexible",
          "Swipe actions for quick status change",
          "Tap card → opens detail view",
          "Pull-to-refresh",
          "Badge count on tab for overdue items",
        ],
      },
      { id: "UX-93", title: "Task/Routine List — Historical", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-93",
        prototypeUrl: `${PROTO_BASE}/proto/task-lifecycle`,
        prd: "Historical archive of completed and cancelled tasks and routines on desktop/iPad. Read-only list for auditing and reference. Filterable by: property, assignee, date range, type (task/routine), completion status (completed/cancelled). Sortable by completion date. Click to view full detail including field notes, photos, and activity log. Exportable for reporting. This is the 'what happened' view for accountability and service history.",
        successCriteria: [
          "Only completed and cancelled items shown",
          "Filter by: property, assignee, date range, type, completion status",
          "Sort by completion date (newest first default)",
          "Click row → opens read-only detail with full history",
          "Export to CSV or PDF for reporting",
          "Search by title, property, or assignee",
          "Pagination for large datasets",
        ],
      },
      { id: "UX-131", title: "Routine Creation — Template", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-131",
        prd: "Routine creation from a predefined template on desktop/iPad. Template library with common property management routines (e.g., Weekly Pool Check, Monthly HVAC Inspection, Seasonal Winterization). PM selects template, reviews the pre-built checklist, customizes (add/remove/reorder actions), assigns to a team member, sets property and schedule (frequency + start date). Each checklist action has: description, expected result (pass/fail criteria), photo required toggle, notes required toggle. Template saves as a new routine instance — editing the instance does not modify the original template.",
        successCriteria: [
          "Template library with categorized routine templates",
          "Select template → pre-filled checklist shown for review",
          "Add, remove, reorder checklist actions",
          "Each action: description, pass/fail criteria, photo required toggle, notes required toggle",
          "Assign to team member",
          "Set property and schedule (frequency + start date)",
          "Editing instance does not modify original template",
          "Save creates routine and first scheduled instance",
        ],
      },
      { id: "UX-144", title: "Routine Creation — Scratch", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-144",
        prd: "Routine creation from scratch on desktop/iPad. PM builds a custom checklist step by step. Checklist builder: add actions with description, pass/fail criteria, photo required, notes required. Drag to reorder actions. Fields: routine name (required), property (required), description, assignee, schedule (frequency + start date), estimated duration. Cassi may suggest actions based on property type and assets ('This property has a pool — add water chemistry check?'). Option to save as template for reuse.",
        successCriteria: [
          "Checklist builder: add actions with description, pass/fail, photo toggle, notes toggle",
          "Drag to reorder actions",
          "Required fields: routine name, property, at least one action",
          "Assignee picker and schedule configuration",
          "Cassi suggestions for actions based on property/asset context",
          "Option to save routine as a reusable template",
          "Save creates routine and first scheduled instance",
          "Preview mode to review checklist before saving",
        ],
      },
      { id: "UX-155", title: "Routine Card", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-155",
        prototypeUrl: `${PROTO_BASE}/proto/review-queue`,
        prd: "Routine instance detail card on desktop/iPad. Shows a single scheduled instance of a routine. Opens as slide panel over calendar. Header: routine name, property, assignee, scheduled date, status (Pending/In Progress/Completed). Checklist section: each action shown as a row with pass/fail toggle, photo capture slot, notes field, and flag button. Assignee executes action-by-action: taps pass or fail, captures photo if required, adds notes. Flagging an action marks it for PM review with a reason. Issue detection: if an action is failed, Cassi suggests creating a follow-up task. Completion requires all actions to have a pass/fail result. Summary section shows: total pass/fail counts, flagged items, time spent, and option to generate report (see UX-292).",
        successCriteria: [
          "Routine instance header: name, property, assignee, date, status",
          "Checklist: each action with pass/fail toggle, photo slot, notes, flag button",
          "Action-by-action execution: pass/fail required for each",
          "Photo capture per action when required",
          "Flag action with reason for PM review",
          "Failed action triggers Cassi suggestion to create follow-up task",
          "Completion blocked until all actions have pass/fail",
          "Summary: pass/fail counts, flagged items, time spent",
          "Generate Report action links to routine report flow",
        ],
      },
      { id: "UX-160", title: "Routine Card", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-160",
        prototypeUrl: `${PROTO_BASE}/proto/review-queue`,
        prd: "Mobile routine execution card — the primary field tech view for completing routines. Full-screen, action-by-action flow. Each action shown one at a time (or as a scrollable checklist). Pass/fail buttons large and thumb-friendly. Camera opens directly for photo capture. Notes via keyboard or voice. Flag button with reason picker. Progress indicator showing completed/total actions. Cannot skip actions — must pass or fail each. On completion, summary screen with option to flag the whole routine for PM review.",
        successCriteria: [
          "Action-by-action execution with large pass/fail buttons",
          "Camera opens directly for photo capture per action",
          "Notes entry via keyboard",
          "Flag action with reason",
          "Progress indicator: completed / total actions",
          "All actions must be passed or failed before completion",
          "Completion summary screen with flag-for-review option",
          "Routine completion under 5 minutes for a 10-action checklist",
        ],
      },
    ],
  },

  // ── 6. Reports ────────────────────────────────────────────
  {
    id: 6,
    name: "Reports",
    linearProjectId: "4e357db1-beab-4610-a6a1-0ae2a34cd563",
    linearUrl: "https://linear.app/cassi/project/reports-338e4d4327b1",
    status: "Planned",
    targetDate: "May 5",
    color: "#4cb782",
    context: {
      problem: "PMs need an easy way to create service reports for homeowners but it takes too long manually. Inspection checklists export broken in customer-facing view. No structured report generation from routine results.",
      hypothesis: "AI-generated reports from routine/inspection results — PM reviews, edits, sends — turns a 30-minute writing task into a 3-minute review. Homeowners get professional reports that build trust and justify service fees.",
      evidence: [
        { text: "Inspection checklist — within 2 taps, company-defined checklist, check items off, export PDF to homeowner.", source: "Neversweat Apr 15", person: "Michael" },
        { text: "Checklist export broken — looked correct internally, broken in customer-facing view.", source: "Neversweat (bug report)" },
      ],
      successSignal: "Admin can review, edit, and send a homeowner report in under 3 minutes. AI narrative is usable without editing in 80%+ of cases.",
    },
    issues: [
      { id: "UX-292", title: "Routine Report", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-292",
        prd: "AI-generated report from a completed routine instance on desktop/iPad. Triggered from the routine card completion summary. Cassi generates a professional narrative report from the checklist results: property name, date, technician, each action with pass/fail result, photos, notes, and flagged items. PM reviews the generated narrative in an editor — can edit text, reorder sections, add/remove photos, and add PM commentary. Send to homeowner via email (rendered as branded PDF or HTML email). Report includes: company branding, property address, routine summary, action-by-action results with photos, flagged items highlighted, and PM notes. Success state: report sent confirmation. Error state: generation failure with retry, or send failure with retry.",
        successCriteria: [
          "AI generates narrative report from routine results",
          "PM can edit generated text, reorder sections, add/remove photos",
          "PM can add commentary before sending",
          "Send via email as branded PDF or HTML",
          "Report includes: company branding, property, date, tech, action results, photos",
          "Flagged items highlighted in report",
          "Success state: sent confirmation with preview link",
          "Error state: generation failure with retry action",
          "Error state: send failure with retry action",
          "Report preview before send",
        ],
        children: [
          { id: "UX-293", title: "Success", label: "page state" },
          { id: "UX-294", title: "Error", label: "page state" },
        ],
      },
      { id: "UX-295", title: "Task/Routine List Report", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-295",
        prd: "Aggregate periodic report from task and routine list data on desktop/iPad. PM selects a property (or all properties), date range, and report type (tasks only, routines only, or both). Cassi generates a summary report: total tasks/routines completed, pass/fail rates for routines, overdue items, time spent, and narrative summary of work performed. Useful for monthly/quarterly homeowner updates or internal reviews. PM can edit the generated narrative, add commentary, and send to homeowner or export as PDF. Success state: report generated and ready for review/send. Error state: insufficient data or generation failure with clear message.",
        successCriteria: [
          "Property selector (single property or all)",
          "Date range picker for report period",
          "Report type: tasks, routines, or both",
          "AI-generated summary: completion counts, pass/fail rates, overdue items, time spent",
          "Narrative summary of work performed",
          "PM can edit narrative and add commentary",
          "Send via email or export as PDF",
          "Success state: report ready for review and send",
          "Error state: insufficient data message or generation failure with retry",
          "Report preview before send/export",
        ],
        children: [
          { id: "UX-296", title: "Success", label: "page state" },
          { id: "UX-297", title: "Error", label: "page state" },
        ],
      },
    ],
  },

  // ── 7. Team & Vendors ─────────────────────────────────────
  {
    id: 7,
    name: "Team & Vendors",
    linearProjectId: "8a4c4ff9-298d-493a-baf8-b76587803b18",
    linearUrl: "https://linear.app/cassi/project/team-and-vendors-f605474cbeb0",
    status: "Planned",
    targetDate: "May 8",
    color: "#4cb782",
    prototypeUrl: `${PROTO_BASE}/proto/vendor-module`,
    context: {
      problem: "Vendor coordination is entirely ad hoc — contacts and tasks are not connected. Subcontractors won't use a portal; all communication must go outbound from Cassi. Team dispatch exists in the PM's head. No way to see who's available, overbooked, or off.",
      hypothesis: "Vendors as first-class entities with task-driven notifications (Cassi sends, PM approves) eliminates manual email/text coordination. Team dispatch with availability constraints prevents overbooking and makes scheduling decisions visible.",
      evidence: [
        { text: "It'd be interesting to see where this certain vendor is in terms of all the projects.", source: "Neversweat Apr 15", person: "Michael" },
        { text: "Some guys who we use a lot, I would make them get onto it.", source: "Neversweat Apr 15", person: "Michael" },
        { text: "I don't think they have to be associated with the app. I think that could just be like a job where we have to go let them in.", source: "Neversweat Apr 15", person: "Michael" },
        { text: "Big burly guys who don't like phones won't use a PM app.", source: "Neversweat Apr 15", person: "Michael" },
        { text: "The software is 'almost useless' without Gmail integration for his use case.", source: "JC Contracting Apr 8", person: "Bayron" },
      ],
      successSignal: "Admin never has to manually compose an email or text to a vendor. Vendor outbound status gives at-a-glance visibility into who's been notified and who's confirmed.",
      researchFlags: [
        "Vendor access tiers: heavy/recurring = lightweight app user; one-off = job ticket only. V1 covers outbound notification; vendor app access is post-v1.",
        "Subcontractor communication is a distinct workflow — JC Contracting's entire business runs through subs. The request → work order → confirmation loop happens outside Cassi today. This is a hard adoption blocker.",
        "Vendor search unreliable in beta — added vendors take a long time to appear, if at all.",
      ],
    },
    issues: [
      { id: "UX-240", title: "Team List", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-240",
        prd: "Team list view on desktop/iPad showing all team members in the organization. Opens as a canvas overlay from nav. Each member card shows: name, role (Admin/PM/Field), utilization status (Open/Overbooked), active task count, assigned properties count, and avatar. Search by name. Filter by role. Click member to open team member profile. Add Team Member button triggers invite flow. Sorted by name or utilization status.",
        successCriteria: [
          "All team members listed with name, role, utilization status, task count, property count",
          "Search by name",
          "Filter by role: Admin, PM, Field",
          "Click member → opens team member profile",
          "Add Team Member button → invite flow",
          "Utilization status badge: Open (green) / Overbooked (red/amber)",
          "Empty state with prompt to add first team member",
          "Canvas overlay from nav",
        ],
      },
      { id: "UX-244", title: "Team List", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-244",
        prd: "Mobile team list. Card-based list of all team members with name, role, utilization badge, and active task count. Search and filter by role. Tap member to open profile. Pull-to-refresh. Add Team Member action accessible from this view (Admin only).",
        successCriteria: [
          "All team members in card list",
          "Name, role, utilization badge, active task count per card",
          "Search by name",
          "Filter by role",
          "Tap → opens team member profile",
          "Add Team Member action (Admin only)",
          "Pull-to-refresh",
        ],
      },
      { id: "UX-248", title: "Add a Team Member", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-248",
        prd: "Invite flow for adding a new team member on desktop/iPad. Admin only. Fields: name, email, phone, role (Admin/PM/Field). Sends an invite via email or SMS. Invited member appears in team list with 'Invited' status until they accept. Admin can resend invite or cancel. After acceptance, member is active and can be assigned to properties and tasks. Optional: set initial working hours and assign to properties during invite.",
        successCriteria: [
          "Admin-only action (not visible to PM/Field roles)",
          "Fields: name, email, phone, role selector",
          "Send invite via email or SMS",
          "Invited member shows in team list with 'Invited' status",
          "Resend invite action",
          "Cancel invite action",
          "Optional: set working hours and assign properties during invite",
          "Validation: email/phone format, duplicate detection",
        ],
      },
      { id: "UX-251", title: "Team Member Profile", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-251",
        prd: "Team member profile on desktop/iPad. Sections: Overview (name, role, contact info, utilization status), Working Hours (daily schedule with start/end times per day of week, editable by Admin), Assigned Properties (list of properties this member manages/services), Active Tasks (current open and in-progress tasks), Schedule (link to individual schedule view UX-186). Admin can edit: role, working hours, property assignments. Admin can deactivate a team member (removes from scheduling but preserves history).",
        successCriteria: [
          "Overview: name, role, contact info, utilization status",
          "Working hours: per day-of-week start/end times, editable by Admin",
          "Assigned properties list",
          "Active tasks list with status",
          "Link to individual schedule view",
          "Admin can edit role, working hours, property assignments",
          "Deactivate member action with confirmation (preserves history)",
          "Contact actions: email, call, text directly from profile",
        ],
      },
      { id: "UX-255", title: "Team Member Profile", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-255",
        prd: "Mobile team member profile. Same sections as desktop in a vertical scroll layout. Admin can edit working hours and property assignments. Contact actions (call, text, email) prominent at top. Tap-to-call and tap-to-text for quick communication. Active tasks shown as compact card list.",
        successCriteria: [
          "All profile sections in vertical scroll",
          "Contact actions: tap-to-call, tap-to-text, tap-to-email",
          "Admin can edit working hours and property assignments",
          "Active tasks as compact card list",
          "Deactivate member action (Admin only)",
        ],
      },
      { id: "UX-261", title: "Vendor List", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-261",
        prototypeUrl: `${PROTO_BASE}/proto/vendor-module`,
        prd: "Vendor list view on desktop/iPad. Opens as a canvas overlay from nav. Shows all vendors in the organization. Each vendor card: company name, category (HVAC, Plumbing, Electrical, Landscaping, etc.), primary contact name, phone, status (Active/Inactive), assigned properties count, and active task count. Search by name or category. Filter by: status, category, assigned property. Sort by name, category, or last activity. Click vendor to open vendor profile. Add Vendor button triggers creation flow.",
        successCriteria: [
          "All vendors listed with: name, category, contact, status, property count, task count",
          "Search by name or category",
          "Filter by: status (Active/Inactive), category, assigned property",
          "Sort by name, category, or last activity",
          "Click vendor → opens vendor profile",
          "Add Vendor button → creation flow",
          "Empty state with prompt to add first vendor",
          "Canvas overlay from nav",
        ],
      },
      { id: "UX-265", title: "Vendor List", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-265",
        prototypeUrl: `${PROTO_BASE}/proto/vendor-module`,
        prd: "Mobile vendor list. Card-based list with vendor name, category, status badge, and primary contact. Search and filter by category/status. Tap vendor to open profile. Tap phone number to call directly. Pull-to-refresh. Add Vendor action accessible.",
        successCriteria: [
          "All vendors in card list with name, category, status, contact",
          "Search by name or category",
          "Filter by status and category",
          "Tap vendor → opens profile",
          "Tap phone → direct call",
          "Add Vendor action",
          "Pull-to-refresh",
        ],
      },
      { id: "UX-269", title: "Vendor Profile", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-269",
        prototypeUrl: `${PROTO_BASE}/proto/vendor-module`,
        prd: "Vendor profile on desktop/iPad. Sections: Overview (company name, category, primary contact, phone, email, preferred communication channel — email/SMS/phone), Notes (running log of vendor-related notes), Task History (all tasks assigned to this vendor with status and dates), Properties (properties this vendor is associated with), Outbound Notifications (log of messages sent to this vendor via Cassi — see below). Task-driven outbound notifications: when a task is assigned to a vendor, Cassi generates a notification message (work order summary) that PM reviews and taps 'Send' to deliver via the vendor's preferred channel. PM can edit the message before sending. Notification log shows: message, channel, sent timestamp, and delivery/response status. Admin can edit all vendor fields. Admin can deactivate vendor (preserves history).",
        successCriteria: [
          "Overview: name, category, contact info, preferred communication channel",
          "Notes section: running log with add/edit",
          "Task History: all vendor tasks with status, dates, property",
          "Properties: associated properties list",
          "Outbound Notifications: log of sent messages with status",
          "Task-driven notification: Cassi generates message, PM edits and sends",
          "Message sent via vendor's preferred channel (email/SMS)",
          "Notification log: message, channel, timestamp, delivery status",
          "Admin can edit all fields and deactivate vendor",
        ],
      },
      { id: "UX-274", title: "Vendor Profile", platform: "Mobile Admin", status: "Todo", url: "https://linear.app/cassi/issue/UX-274",
        prototypeUrl: `${PROTO_BASE}/proto/vendor-module`,
        prd: "Mobile vendor profile for Admin. Same sections as desktop in vertical scroll. Admin has full edit access. Contact actions prominent: tap-to-call, tap-to-text, tap-to-email. Task-driven outbound notifications: Admin reviews Cassi-generated message and taps Send. Notification log scrollable. Admin can edit vendor fields and deactivate.",
        successCriteria: [
          "All profile sections in vertical scroll",
          "Contact actions: tap-to-call, tap-to-text, tap-to-email",
          "Full edit access for Admin",
          "Outbound notification: review and send Cassi-generated message",
          "Notification log with delivery status",
          "Deactivate vendor action with confirmation",
        ],
      },
      { id: "UX-279", title: "Vendor Profile", platform: "Mobile PM", status: "Todo", url: "https://linear.app/cassi/issue/UX-279",
        prototypeUrl: `${PROTO_BASE}/proto/vendor-module`,
        prd: "Mobile vendor profile for PM role. Read-only view of vendor details — PM can see contact info, notes, task history, and properties but cannot edit vendor-level fields. Contact actions available: tap-to-call, tap-to-text. PM can view outbound notification log but cannot send notifications (Admin only). Useful for field reference — PM knows who the vendor is and how to reach them.",
        successCriteria: [
          "Vendor details viewable: name, category, contact, notes, task history",
          "Contact actions: tap-to-call, tap-to-text",
          "No edit access to vendor fields",
          "Outbound notification log viewable (read-only)",
          "No send notification action",
          "Properties association visible",
        ],
      },
      { id: "UX-283", title: "Add a Vendor", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-283",
        prototypeUrl: `${PROTO_BASE}/proto/vendor-module`,
        prd: "Add vendor flow on desktop/iPad. Fields: company name (required), category (required — HVAC, Plumbing, Electrical, Landscaping, General, Custom), primary contact name, phone, email, preferred communication channel (email/SMS/phone), notes, assigned properties (multi-select from property list). Vendor is Active on creation. Duplicate detection: warns if a vendor with the same name or phone already exists. Save adds vendor to the vendor list and makes them available for task assignment.",
        successCriteria: [
          "Required fields: company name, category",
          "Category selector with predefined options and custom entry",
          "Contact fields: name, phone, email, preferred channel",
          "Notes field for initial vendor notes",
          "Property assignment: multi-select from org properties",
          "Duplicate detection: warning on matching name or phone",
          "Save creates Active vendor, available for task assignment",
          "Validation: phone/email format checking",
        ],
      },
      { id: "UX-288", title: "Add a Vendor", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-288",
        prototypeUrl: `${PROTO_BASE}/proto/vendor-module`,
        prd: "Mobile add vendor flow. Same fields as desktop optimized for mobile input. Quick-add: company name + category + phone is the minimum to create. Full details can be added later from the vendor profile. Contact import from phone contacts as a shortcut. Save creates Active vendor immediately.",
        successCriteria: [
          "Quick-add: company name + category + phone minimum",
          "All desktop fields available for full entry",
          "Contact import from phone contacts",
          "Category selector with predefined options and custom",
          "Save creates Active vendor",
          "Duplicate detection warning",
          "Form state preserved on interruption",
        ],
      },
    ],
  },

  // ── 8. Company Onboarding ─────────────────────────────────
  {
    id: 8,
    name: "Company Onboarding",
    linearProjectId: "b5c389c2-edcb-4b3e-a48a-db5c6f1673aa",
    linearUrl: "https://linear.app/cassi/project/company-onboarding-9d58c9d86f76",
    status: "Backlog",
    targetDate: "May 13",
    color: "#bec2c8",
    prototypeUrl: `${PROTO_BASE}/proto/welcome-flow`,
    context: {
      problem: "New companies signing up need to see value immediately. Current onboarding asks too much too soon. PMs are busy — they won't fill forms if they don't see the payoff.",
      hypothesis: "A Cassi-led conversational onboarding (not forms) captures what's needed, builds the first property automatically, and lands the PM on a dashboard that already has structure — not an empty shell.",
      evidence: [
        { text: "I could learn this in a couple hours.", source: "Old World", person: "Patrick" },
      ],
      successSignal: "New company goes from signup to first property onboarded in under 10 minutes.",
      researchFlags: [
        "Company with 1 person (solo PM) — skip team setup step.",
        "No tickets created yet — needs full breakdown before May 13.",
      ],
    },
    issues: [],
  },

  // ── 9. Profile & Settings ─────────────────────────────────
  {
    id: 9,
    name: "Profile & Settings",
    linearProjectId: "ac3654fd-670e-4b97-8c7d-ca0510c645bf",
    linearUrl: "https://linear.app/cassi/project/profile-and-settings-58f5a0a16c23",
    status: "Backlog",
    targetDate: null,
    color: "#bec2c8",
    context: {
      problem: "No permission enforcement — Admin/PM/Field roles defined but not gated. Notification preferences don't exist. Google/Outlook calendar sync is the #1 integration request.",
      hypothesis: "Settings that work means the PM configures once and forgets. Roles that enforce mean field techs only see what they need. Calendar sync eliminates the 'two calendars' problem.",
      evidence: [
        { text: "Google Calendar sync.", source: "Research Synthesis — feature request across multiple customers" },
      ],
      successSignal: "Team management works end-to-end — invite, set role, assign to properties. Settings are persistent across sessions.",
      researchFlags: [
        "Roles & permissions enforcement deferred to post-v1. V1 has the UI but doesn't enforce at API level.",
      ],
    },
    issues: [
      { id: "UX-307", title: "Roles & Permissions", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-307",
        prd: "Roles and permissions management screen on desktop/iPad. Shows the three roles (Admin, PM, Field) with a matrix of what each role can do: Admin (full access — manage properties, team, vendors, settings, approve tasks, send reports), PM (manage assigned properties, execute tasks/routines, view team/vendors, cannot change settings or roles), Field (execute assigned tasks/routines only, cannot access properties/team/vendors/settings). Admin can view the permission matrix but cannot customize it in v1 (permissions are fixed). Admin can change a team member's role from this screen or from their profile. V1 displays the matrix as documentation — enforcement at the API level is post-v1.",
        successCriteria: [
          "Permission matrix displayed: Admin, PM, Field roles vs. capabilities",
          "Each capability row clearly shows which roles have access",
          "Admin can change a team member's role from this view",
          "Role change confirmation dialog",
          "Read-only matrix — no custom permission editing in v1",
          "Clear indication that this is the reference for role capabilities",
        ],
      },
      { id: "UX-314", title: "Roles & Permissions", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-314",
        prd: "Mobile roles and permissions view. Same permission matrix as desktop in a mobile-optimized layout (accordion or card-based per role). Admin can change team member roles. Read-only matrix — no custom permissions in v1.",
        successCriteria: [
          "Permission matrix in mobile-friendly format (accordion or cards)",
          "Each role expandable to show capabilities",
          "Admin can change a team member's role",
          "Role change confirmation dialog",
          "Read-only — no custom permission editing",
        ],
      },
      { id: "UX-315", title: "Profile", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-315",
        prd: "User profile screen on desktop/iPad. Shows and allows editing of: name, email, phone number, role (read-only — only Admin can change), avatar/photo. Email and phone are used for login and notifications. Changes save immediately with confirmation toast. Email change requires verification (confirmation email sent). Phone change requires SMS verification.",
        successCriteria: [
          "Display: name, email, phone, role, avatar",
          "Edit name: inline edit with save",
          "Edit email: triggers verification flow (confirmation email)",
          "Edit phone: triggers SMS verification",
          "Role shown as read-only (Admin changes role elsewhere)",
          "Avatar/photo upload or change",
          "Save confirmation toast on successful update",
          "Validation: email format, phone format",
        ],
      },
      { id: "UX-316", title: "Profile", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-316",
        prd: "Mobile user profile. Same fields as desktop in a vertical form layout. Camera integration for avatar/photo capture or upload. Same verification flows for email and phone changes. Accessible from settings/more menu.",
        successCriteria: [
          "Display and edit: name, email, phone, avatar",
          "Role shown as read-only",
          "Camera integration for avatar photo",
          "Email change triggers verification",
          "Phone change triggers SMS verification",
          "Save confirmation on update",
        ],
      },
      { id: "UX-319", title: "Preferences", platform: "Desktop / iPad", status: "Todo", url: "https://linear.app/cassi/issue/UX-319",
        prd: "Preferences screen on desktop/iPad. Sections: Notifications (toggle push notifications, email notifications, notification types — overdue tasks, QA pending, vendor responses, Cassi suggestions), Calendar Integration (connect Google Calendar or Outlook Calendar — OAuth flow, sync direction: one-way from Cassi to external or two-way, which calendars to sync). Settings persist across sessions and devices. Changes save immediately with confirmation.",
        successCriteria: [
          "Notification preferences: toggle push and email notifications",
          "Notification types configurable: overdue, QA pending, vendor, Cassi suggestions",
          "Google Calendar integration: OAuth connect flow",
          "Outlook Calendar integration: OAuth connect flow",
          "Sync direction setting: one-way (Cassi → external) or two-way",
          "Calendar selection: which external calendars to sync",
          "Connected status shown with disconnect option",
          "Settings persist across sessions and devices",
          "Changes save immediately with confirmation toast",
        ],
      },
      { id: "UX-317", title: "Preferences", platform: "Mobile", status: "Todo", url: "https://linear.app/cassi/issue/UX-317",
        prd: "Mobile preferences. Same settings as desktop: notification toggles, calendar integration. Push notification permission request handled natively (iOS/Android permission dialog triggered on first toggle). Calendar integration uses native OAuth flow. Settings sync with desktop — changes on either platform reflect everywhere.",
        successCriteria: [
          "Notification toggles: push and email, per notification type",
          "Push notification permission request on first enable",
          "Google Calendar connect via native OAuth",
          "Outlook Calendar connect via native OAuth",
          "Sync direction and calendar selection",
          "Settings sync across platforms",
          "Changes save immediately with confirmation",
        ],
      },
    ],
  },
];
